USE WISHLIST_DESAFIO;

-----Contagem dos elementos das tabelas

SELECT COUNT (NOME) AS QUANTIDADE_VERBOS
FROM VERBOS

SELECT COUNT (NOME) AS QUANTIDADE_USUARIOS
FROM USUARIOS

SELECT COUNT (ID) AS QUANTIDADE_DESEJOS
FROM DESEJOS


-----Ordenação da Data de Criação

SELECT * FROM DESEJOS ORDER BY DATA_CRIACAO ASC
SELECT * FROM DESEJOS ORDER BY DATA_CRIACAO DESC


-----Todos os Usuários e seus desejos
GO
CREATE VIEW DESEJOS_VERBOS_VIEW AS
SELECT
	USUARIOS.NOME AS NOME_USUARIO,
	VERBOS.NOME AS NOME_VERBO,
	DESEJOS.DATA_CRIACAO,
	DESEJOS.DESCRICAO
FROM
	DESEJOS
	INNER JOIN
	USUARIOS ON DESEJOS.ID_USUARIO = USUARIOS.ID
	INNER JOIN
	VERBOS ON DESEJOS.ID_VERBO = VERBOS.ID
GO

SELECT * FROM  DESEJOS_VERBOS_VIEW


-----Filtrando Desejos por Verbos
SELECT * FROM DESEJOS_VERBOS_VIEW WHERE NOME_VERBO = 'Comprar'


-----Filtrando Desejo pelo nome do Usuário
SELECT * FROM DESEJOS_VERBOS_VIEW WHERE NOME_USUARIO = 'Cândida'




-----Deletar  VIEW:
DROP VIEW DESEJOS_VERBOS_VIEW