CREATE DATABASE WISHLIST_DESAFIO;

USE WISHLIST_DESAFIO;

CREATE TABLE VERBOS (
	ID INT IDENTITY PRIMARY KEY 
	,NOME VARCHAR (100) NOT NULL UNIQUE
);

CREATE TABLE USUARIOS (
	ID INT IDENTITY PRIMARY KEY 
	,NOME VARCHAR (255) NOT NULL
	,EMAIL VARCHAR (250) NOT NULL UNIQUE
	,SENHA VARCHAR (255) NOT NULL
);

CREATE TABLE DESEJOS (
	ID INT IDENTITY PRIMARY KEY 
	,ID_VERBO INT FOREIGN KEY REFERENCES VERBOS(ID)
	,DESCRICAO TEXT NOT NULL
	,DATA_CRIACAO DATE NOT NULL
	,ID_USUARIO INT FOREIGN KEY REFERENCES USUARIOS(ID)
);